# User validator
NAME_REGEX='^[A-Za-z]*$'                                # David, Jeniffer, John, Will, Peter, Chriss
NAME_MIN_LEN = 2
NAME_MAX_LEN = 15
ADDRESS_REGEX = '^([A-Za-z]*\s)*[0-9]+\s?[a-zA-Z]?$'    # Amager Boulevard 23, Amager Strand Vej 14 A, Amager Strand Vej 144, Amager Strand Vej 144 a
ADDRESS_MIN_LEN = 5
ADDRESS_MAX_LEN = 40
AGE_REGEX = '^\d?\d$'                                   # 1, 12, 75, 31
AGE_MIN = 18
AGE_MAX = 99
USERNAME_REGEX = '^([A-Za-z0-9]{2,20}\s?_?){1,3}$'      # Big_Green cucumber11, BigGreencucumber11, big_green_cucumber11, big_green_cucumber
USERNAME_MIN_LENGTH = 10
USERNAME_MAX_LENGHT = 30
EMAIL_REGEX = '^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
EMAIL_MIN_LEN = 10
EMAIL_MAX_LEN = 40
PASSWORD_REGEX = '^[A-Za-z0-9\#+\$+\!+]*$'              # dahow124# dadadpop! 14yzti$
PASSWORD_MIN_LEN = 8
PASSWORD_MAX_LEN = 16